service:
  name: my-graphql-service

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    SERVICE: ${self:service}
    STAGE: ${opt:stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # Use http keep-alive for AWS connections

functions:
  graphQl:
    handler: src/graphQL/index.graphQlHandler
    events:
      - http:
          path: /graphql
          method: post
          cors: true

  playground:
    handler: src/graphQL/index.playgroundHandler
    events:
      - http:
          path: /playground
          method: get
          cors: true
          # TODO: Consider securing this unless your API is public
